import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface OrderRequest {
  recipient_name?: string;
  recipient_phone?: string;
  recipient_address: string;
  user_id?: string;
  channel?: string;
}

interface ShippingUpdate {
  shipping_carrier?: string;
  tracking_number?: string;
  tracking_url?: string;
}

interface StatusUpdate {
  status: string;
  note?: string;
}

Deno.serve(async (req) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY")!;

  // Get auth header for admin operations
  const authHeader = req.headers.get("Authorization");
  
  const url = new URL(req.url);
  const pathParts = url.pathname.split("/").filter(Boolean);
  // Path format: /kit-orders/{action?}/{id?}
  const action = pathParts[1] || "";
  const id = pathParts[2] || "";

  try {
    // POST /kit-orders - Create new order (requires authentication)
    if (req.method === "POST" && !action) {
      if (!authHeader) {
        return new Response(
          JSON.stringify({ error: "Authorization required" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const userClient = createClient(supabaseUrl, supabaseAnonKey, {
        global: { headers: { Authorization: authHeader } },
      });
      const { data: { user }, error: authErr } = await userClient.auth.getUser();
      if (authErr || !user) {
        return new Response(
          JSON.stringify({ error: "Invalid token" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const body: OrderRequest = await req.json();

      if (!body.recipient_address) {
        return new Response(
          JSON.stringify({ error: "recipient_address is required" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Validate input lengths to prevent DoS and ensure data quality
      if (body.recipient_name && body.recipient_name.length > 200) {
        return new Response(
          JSON.stringify({ error: "Recipient name too long (max 200 characters)" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      if (body.recipient_phone && body.recipient_phone.length > 20) {
        return new Response(
          JSON.stringify({ error: "Phone number too long (max 20 characters)" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      if (body.recipient_address.length > 500) {
        return new Response(
          JSON.stringify({ error: "Address too long (max 500 characters)" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Use service role for creating orders
      const supabase = createClient(supabaseUrl, supabaseServiceKey);

      const { data: order, error } = await supabase
        .from("kit_orders")
        .insert({
          recipient_name: body.recipient_name || null,
          recipient_phone: body.recipient_phone || null,
          recipient_address: body.recipient_address,
          // Always derive user_id from the verified token — never trust body.user_id
          user_id: user.id,
          order_code: "", // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) {
        return new Response(
          JSON.stringify({ error: error.message }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Create order event
      await supabase.from("kit_order_events").insert({
        order_id: order.id,
        event_type: "created",
        event_description: `Order created via ${body.channel || "API"}`,
        created_by: user.id,
        is_admin_event: false,
      });

      return new Response(
        JSON.stringify({
          success: true,
          order_id: order.id,
          order_code: order.order_code,
          status: order.status,
          display_name: "Self-care kit",
          created_at: order.created_at,
        }),
        { status: 201, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }


    // GET /kit-orders/by-code/{code} - Get order by code (public)
    // Uses the secure kit_order_tracking view which excludes PII
    if (req.method === "GET" && action === "by-code" && id) {
      const supabase = createClient(supabaseUrl, supabaseAnonKey);

      // Use the secure tracking view instead of kit_orders table
      // This view excludes sensitive PII (recipient_name, phone, address)
      const { data: order, error } = await supabase
        .from("kit_order_tracking")
        .select(`
          order_code, status, shipping_carrier, tracking_number, tracking_url,
          created_at, updated_at, packed_at, shipped_at, out_for_delivery_at, 
          delivered_at, received_at, display_name
        `)
        .eq("order_code", id.toUpperCase())
        .maybeSingle();

      if (error) {
        return new Response(
          JSON.stringify({ error: error.message }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      if (!order) {
        return new Response(
          JSON.stringify({ error: "Order not found" }),
          { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Note: We can't fetch events by order_id since the view doesn't expose id
      // Events are only shown for authenticated users viewing their own orders
      return new Response(
        JSON.stringify({
          order_code: order.order_code,
          display_name: order.display_name || "Self-care kit",
          status: order.status,
          shipping_carrier: order.shipping_carrier,
          tracking_number: order.tracking_number,
          tracking_url: order.tracking_url,
          timeline: {
            requested: order.created_at,
            packed: order.packed_at,
            shipped: order.shipped_at,
            out_for_delivery: order.out_for_delivery_at,
            delivered: order.delivered_at,
            received: order.received_at,
          },
          events: [], // Events not available in public view for security
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // GET /kit-orders/by-user/{user_id} - Get orders by user (auth required; owner or admin only)
    if (req.method === "GET" && action === "by-user" && id) {
      if (!authHeader) {
        return new Response(
          JSON.stringify({ error: "Authorization required" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const userClient = createClient(supabaseUrl, supabaseAnonKey, {
        global: { headers: { Authorization: authHeader } },
      });
      const { data: { user }, error: authErr } = await userClient.auth.getUser();
      if (authErr || !user) {
        return new Response(
          JSON.stringify({ error: "Invalid token" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Allow only the requested user themselves, or an admin, to list orders
      let allowed = user.id === id;
      if (!allowed) {
        const { data: isAdmin } = await userClient.rpc("has_role", {
          _user_id: user.id,
          _role: "admin",
        });
        allowed = !!isAdmin;
      }
      if (!allowed) {
        return new Response(
          JSON.stringify({ error: "Forbidden" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const supabase = createClient(supabaseUrl, supabaseServiceKey);

      const { data: orders, error } = await supabase
        .from("kit_orders")
        .select(`
          id, order_code, status, shipping_carrier, tracking_number, tracking_url,
          created_at, updated_at, packed_at, shipped_at, out_for_delivery_at, 
          delivered_at, received_at, display_name
        `)
        .eq("user_id", id)
        .order("created_at", { ascending: false });

      if (error) {
        return new Response(
          JSON.stringify({ error: error.message }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      return new Response(
        JSON.stringify({
          orders: (orders || []).map((o) => ({
            order_code: o.order_code,
            display_name: o.display_name || "Self-care kit",
            status: o.status,
            shipping_carrier: o.shipping_carrier,
            tracking_number: o.tracking_number,
            created_at: o.created_at,
            updated_at: o.updated_at,
          })),
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // PATCH /kit-orders/{order_id}/shipping - Update shipping (admin only)
    if (req.method === "PATCH" && id && pathParts[3] === "shipping") {
      if (!authHeader) {
        return new Response(
          JSON.stringify({ error: "Authorization required" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const supabase = createClient(supabaseUrl, supabaseAnonKey, {
        global: { headers: { Authorization: authHeader } },
      });

      // Check if user is admin
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        return new Response(
          JSON.stringify({ error: "Invalid token" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const { data: isAdmin } = await supabase.rpc("has_role", {
        _user_id: user.id,
        _role: "admin",
      });

      if (!isAdmin) {
        return new Response(
          JSON.stringify({ error: "Admin access required" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const body: ShippingUpdate = await req.json();
      const adminSupabase = createClient(supabaseUrl, supabaseServiceKey);

      const updates: Record<string, unknown> = {
        last_updated_by: user.id,
      };

      if (body.shipping_carrier !== undefined) updates.shipping_carrier = body.shipping_carrier;
      if (body.tracking_number !== undefined) updates.tracking_number = body.tracking_number;
      if (body.tracking_url !== undefined) updates.tracking_url = body.tracking_url;

      // Auto-set status to shipped if tracking is added
      if (body.tracking_number) {
        updates.status = "shipped";
        updates.shipped_at = new Date().toISOString();
      }

      const { data: order, error } = await adminSupabase
        .from("kit_orders")
        .update(updates)
        .eq("id", id)
        .select()
        .single();

      if (error) {
        return new Response(
          JSON.stringify({ error: error.message }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Add event
      await adminSupabase.from("kit_order_events").insert({
        order_id: id,
        event_type: "shipping_update",
        event_description: `Shipping updated: ${body.shipping_carrier || ""} ${body.tracking_number || ""}`,
        created_by: user.id,
        is_admin_event: true,
      });

      return new Response(
        JSON.stringify({ success: true, order }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // PATCH /kit-orders/{order_id}/status - Update status (admin only)
    if (req.method === "PATCH" && id && pathParts[3] === "status") {
      if (!authHeader) {
        return new Response(
          JSON.stringify({ error: "Authorization required" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const supabase = createClient(supabaseUrl, supabaseAnonKey, {
        global: { headers: { Authorization: authHeader } },
      });

      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        return new Response(
          JSON.stringify({ error: "Invalid token" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const { data: isAdmin } = await supabase.rpc("has_role", {
        _user_id: user.id,
        _role: "admin",
      });

      if (!isAdmin) {
        return new Response(
          JSON.stringify({ error: "Admin access required" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const body: StatusUpdate = await req.json();
      const validStatuses = ["requested", "packed", "shipped", "out_for_delivery", "delivered_unconfirmed", "received_confirmed"];
      
      if (!validStatuses.includes(body.status)) {
        return new Response(
          JSON.stringify({ error: "Invalid status", valid_statuses: validStatuses }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const adminSupabase = createClient(supabaseUrl, supabaseServiceKey);

      const updates: Record<string, unknown> = {
        status: body.status,
        last_updated_by: user.id,
      };

      // Set timestamps
      const now = new Date().toISOString();
      if (body.status === "packed") updates.packed_at = now;
      if (body.status === "shipped") updates.shipped_at = now;
      if (body.status === "out_for_delivery") updates.out_for_delivery_at = now;
      if (body.status === "delivered_unconfirmed") updates.delivered_at = now;
      if (body.status === "received_confirmed") updates.received_at = now;

      const { data: order, error } = await adminSupabase
        .from("kit_orders")
        .update(updates)
        .eq("id", id)
        .select()
        .single();

      if (error) {
        return new Response(
          JSON.stringify({ error: error.message }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Add event
      await adminSupabase.from("kit_order_events").insert({
        order_id: id,
        event_type: "status_change",
        event_description: body.note || `Status changed to ${body.status}`,
        created_by: user.id,
        is_admin_event: false,
      });

      return new Response(
        JSON.stringify({ success: true, status: order.status }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // POST /kit-orders/{order_id}/confirm-received - User confirms received (auth required, ownership enforced)
    if (req.method === "POST" && id && pathParts[3] === "confirm-received") {
      if (!authHeader) {
        return new Response(
          JSON.stringify({ error: "Authorization required" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const userClient = createClient(supabaseUrl, supabaseAnonKey, {
        global: { headers: { Authorization: authHeader } },
      });
      const { data: { user }, error: authErr } = await userClient.auth.getUser();
      if (authErr || !user) {
        return new Response(
          JSON.stringify({ error: "Invalid token" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const supabase = createClient(supabaseUrl, supabaseServiceKey);

      // Fetch order and verify ownership before allowing status change
      const { data: order, error: fetchError } = await supabase
        .from("kit_orders")
        .select("id, status, user_id")
        .eq("id", id)
        .maybeSingle();

      if (fetchError || !order) {
        return new Response(
          JSON.stringify({ error: "Order not found" }),
          { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Allow only the order owner, or an admin
      let allowed = order.user_id === user.id;
      if (!allowed) {
        const { data: isAdmin } = await userClient.rpc("has_role", {
          _user_id: user.id,
          _role: "admin",
        });
        allowed = !!isAdmin;
      }
      if (!allowed) {
        return new Response(
          JSON.stringify({ error: "Forbidden" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      if (order.status === "received_confirmed") {
        return new Response(
          JSON.stringify({ error: "Already confirmed" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const { error } = await supabase
        .from("kit_orders")
        .update({
          status: "received_confirmed",
          received_at: new Date().toISOString(),
        })
        .eq("id", id);

      if (error) {
        return new Response(
          JSON.stringify({ error: error.message }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      await supabase.from("kit_order_events").insert({
        order_id: id,
        event_type: "user_confirm_received",
        event_description: "User confirmed receipt of kit",
        created_by: user.id,
        is_admin_event: false,
      });

      return new Response(
        JSON.stringify({
          success: true,
          message: "Thank you for confirming receipt!",
          status: "received_confirmed",
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }


    return new Response(
      JSON.stringify({ error: "Not found" }),
      { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error) {
    console.error("Error:", error);
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
