import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { PageContainer } from "@/components/PageContainer";
import { BottomNav } from "@/components/BottomNav";
import { useLanguage } from "@/lib/i18n";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ArrowLeft, FileText, Plus, X, Download, Copy, Check } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";
import { getUserData } from "@/lib/store";

export default function ConsultationForm() {
  const navigate = useNavigate();
  const { t, language } = useLanguage();
  const { user } = useAuth();
  const [preventionUse, setPreventionUse] = useState("");
  const [recentTesting, setRecentTesting] = useState("");
  const [questions, setQuestions] = useState<string[]>([""]);
  const [saving, setSaving] = useState(false);
  const [copied, setCopied] = useState(false);

  const userData = getUserData();

  const addQuestion = () => {
    if (questions.length < 5) {
      setQuestions([...questions, ""]);
    }
  };

  const removeQuestion = (index: number) => {
    setQuestions(questions.filter((_, i) => i !== index));
  };

  const updateQuestion = (index: number, value: string) => {
    const newQuestions = [...questions];
    newQuestions[index] = value;
    setQuestions(newQuestions);
  };

  const handleSave = async () => {
    if (!user) {
      navigate('/auth');
      return;
    }

    setSaving(true);
    try {
      await supabase.from('consultation_forms').insert({
        user_id: user.id,
        prevention_use: preventionUse,
        recent_testing: { date: recentTesting },
        questions: questions.filter((q) => q.trim()),
      });

      toast.success(t('consultation.saved'));
    } catch (error) {
      console.error('Error saving consultation form:', error);
      toast.error(t('common.error'));
    } finally {
      setSaving(false);
    }
  };

  const generateSummary = () => {
    const summary = `
${language === 'th' ? '=== ข้อมูลก่อนพบแพทย์ ===' : '=== Pre-Consultation Summary ==='}

${language === 'th' ? 'การใช้ยาป้องกันปัจจุบัน:' : 'Current Prevention Use:'}
${preventionUse || (language === 'th' ? 'ไม่ได้ระบุ' : 'Not specified')}

${language === 'th' ? 'การตรวจล่าสุด:' : 'Recent Testing:'}
${recentTesting || (language === 'th' ? 'ไม่ได้ระบุ' : 'Not specified')}

${language === 'th' ? 'คำถามสำหรับผู้ให้บริการ:' : 'Questions for Provider:'}
${questions.filter((q) => q.trim()).map((q, i) => `${i + 1}. ${q}`).join('\n') || (language === 'th' ? 'ไม่มี' : 'None')}

${language === 'th' ? 'สถานะปัจจุบัน:' : 'Current Status:'}
- ${language === 'th' ? 'โหมด' : 'Mode'}: ${userData.mode || (language === 'th' ? 'ไม่ได้ตั้งค่า' : 'Not set')}
- ${language === 'th' ? 'ต่อเนื่อง' : 'Streak'}: ${userData.streak} ${language === 'th' ? 'วัน' : 'days'}

${language === 'th' ? 'สร้างโดย testD' : 'Generated by testD'}
    `.trim();

    return summary;
  };

  const handleCopy = async () => {
    const summary = generateSummary();
    await navigator.clipboard.writeText(summary);
    setCopied(true);
    toast.success(t('consultation.copied'));
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <>
      <PageContainer>
        <div className="flex items-center gap-3 mb-6">
          <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold text-foreground">{t('consultation.title')}</h1>
            <p className="text-muted-foreground">{t('consultation.subtitle')}</p>
          </div>
        </div>

        <Card className="p-4 mb-6 bg-primary/5 border-primary/20">
          <div className="flex items-start gap-3">
            <FileText className="h-5 w-5 text-primary shrink-0 mt-0.5" />
            <p className="text-sm text-muted-foreground">{t('consultation.description')}</p>
          </div>
        </Card>

        {/* Prevention Use */}
        <Card className="p-4 mb-4">
          <Label className="text-foreground font-medium">{t('consultation.preventionUse')}</Label>
          <p className="text-xs text-muted-foreground mb-2">{t('consultation.preventionUseDesc')}</p>
          <Textarea
            placeholder={t('consultation.preventionUsePlaceholder')}
            value={preventionUse}
            onChange={(e) => setPreventionUse(e.target.value)}
            rows={3}
          />
        </Card>

        {/* Recent Testing */}
        <Card className="p-4 mb-4">
          <Label className="text-foreground font-medium">{t('consultation.recentTesting')}</Label>
          <p className="text-xs text-muted-foreground mb-2">{t('consultation.recentTestingDesc')}</p>
          <Input
            type="text"
            placeholder={t('consultation.recentTestingPlaceholder')}
            value={recentTesting}
            onChange={(e) => setRecentTesting(e.target.value)}
          />
        </Card>

        {/* Questions */}
        <Card className="p-4 mb-6">
          <div className="flex items-center justify-between mb-2">
            <Label className="text-foreground font-medium">{t('consultation.questions')}</Label>
            {questions.length < 5 && (
              <Button variant="ghost" size="sm" onClick={addQuestion} className="gap-1">
                <Plus className="h-4 w-4" />
                {t('consultation.addQuestion')}
              </Button>
            )}
          </div>
          <p className="text-xs text-muted-foreground mb-3">{t('consultation.questionsDesc')}</p>
          <div className="space-y-2">
            {questions.map((q, index) => (
              <div key={index} className="flex gap-2">
                <Input
                  placeholder={`${t('consultation.question')} ${index + 1}`}
                  value={q}
                  onChange={(e) => updateQuestion(index, e.target.value)}
                  className="flex-1"
                />
                {questions.length > 1 && (
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => removeQuestion(index)}
                    className="shrink-0"
                  >
                    <X className="h-4 w-4" />
                  </Button>
                )}
              </div>
            ))}
          </div>
        </Card>

        <div className="flex gap-3">
          <Button variant="outline" className="flex-1 gap-2" onClick={handleCopy}>
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            {t('consultation.copy')}
          </Button>
          <Button className="flex-1" onClick={handleSave} disabled={saving}>
            {saving ? t('common.saving') : t('common.save')}
          </Button>
        </div>
      </PageContainer>
      <BottomNav />
    </>
  );
}
