// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-branches.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
var list_branches_default = defineTool({
  name: "list_branches",
  title: "List clinic branches",
  description: "List active SWING clinic branches (name, slug, address, phone) available for booking.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("booking_branches").select("id,slug,name_th,name_en,address_th,address_en,phone,status,is_active").eq("is_active", true).order("name_en");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { branches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List clinic services",
  description: "List active bookable clinic services (Thai and English names).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("booking_services").select("id,slug,name_th,name_en,description_th,description_en,is_free_thai,is_free_global_fund,display_order").eq("is_active", true).order("display_order");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-articles.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { z } from "npm:zod@^3.25.76";
var search_articles_default = defineTool3({
  name: "search_articles",
  title: "Search health articles",
  description: "Search published testD health/harm-reduction articles by keyword (matches Thai and English titles/excerpts).",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword to search titles and excerpts."),
    limit: z.number().int().min(1).max(20).default(10).describe("Max results (1-20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const q = query.replace(/[%,]/g, " ");
    const { data, error } = await supabase.from("blog_articles").select("id,slug,title_th,title_en,excerpt_th,excerpt_en,published_at").eq("status", "published").or(
      `title_th.ilike.%${q}%,title_en.ilike.%${q}%,excerpt_th.ilike.%${q}%,excerpt_en.ilike.%${q}%`
    ).order("published_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tzerhfvlrssrashrcbeg";
var mcp_default = defineMcp({
  name: "testd-mcp",
  title: "testD Health MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the testD \xD7 SWING Clinic app: list clinic branches, list bookable services, and search published health/harm-reduction articles.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_branches_default, list_services_default, search_articles_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
